<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Are you sure you want to delete this item?' => '',
    'Create' => '',
    'Create Site Options Types' => '',
    'Create Site Options Values' => '',
    'Create Siteoptions' => '',
    'Delete' => '',
    'ID' => '',
    'Option Alias' => 'Псевдоним параметра',
    'Option Name' => 'Название параметра',
    'Option Type ID' => 'Тип параметра',
    'Reset' => '',
    'Search' => '',
    'Site Options Types' => '',
    'Site Options Values' => '',
    'Siteoptions' => '',
    'Sort' => '',
    'Text Value' => '',
    'Type Alias' => '',
    'Type Name' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Value' => '',
];
